spring:

  # Spring data rest
  datasource:
    url: ${DATABASE_ADDRESS}
    username: ${DATABASE_USERNAME}
    password: ${database-secret-dev}
  liquibase:
    default-schema: ${DATABASE_SCHEMA}
  jpa:
    properties:
      hibernate:
        default_schema: ${DATABASE_SCHEMA}
