spring:

  datasource:
    url: ${DATABASE_ADDRESS}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  cloud:
    aws:
      s3:
        bucket-name: ${AWS_S3_BUCKET_NAME}
        credentials:
          access-key: ${AWS_S3_ACCESS_KEY}
          secret-key: ${AWS_S3_SECRET_KEY}
        hostname: ${AWS_S3_HOSTNAME}
        region:
          static: eu-central-1
          auto: false

  http:
    log-request-details: on