version: '3.8'

services:
  postgresql:
    image: 'postgres:15.1'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: kobit-local
      POSTGRES_USER: kobit
      POSTGRES_DB: kobit-local
    volumes:
      - ./postgres:/var/lib/postgres/data
  pgadmin4:
    image: dpage/pgadmin4:6.18
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_PASSWORD: kobit-local
      PGADMIN_DEFAULT_EMAIL: kobit@local.com
    ports:
      - '80:80'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
  keycloak:
    image: bitnami/keycloak:20.0.3
    environment:
      KEYCLOAK_ADMIN_USER: kobit
      KEYCLOAK_ADMIN_PASSWORD: kobit-local
      KEYCLOAK_DATABASE_USER: kobit
      KEYCLOAK_DATABASE_PASSWORD: kobit-local
    volumes:
      - ./keycloak:/docker-entrypoint-initdb.d
