package de.muenchen.kobit.backend.configuration;

import static org.assertj.core.api.Assertions.assertThat;

import lombok.val;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class JwtTokenUtilTest {

    // contains both of the Admin roles
    private static final String TOKEN_ADMIN =
            "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4Y0JsZnhRdFdmQkVvUEo3YUVabndMQTYzS2l1Y1ZseUlOQm1MRjNoZDZrIn0.eyJleHAiOjE2Nzg4NzE0MDUsImlhdCI6MTY3ODg3MTEwNSwiYXV0aF90aW1lIjoxNjc4ODcxMTA1LCJqdGkiOiI0MGQ2ZTdmNS0xZGM3LTQ4NjEtOGE5OC00NDg1MmYzOWIzNDciLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg4ODgvcmVhbG1zL0tNNTUiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNjRmNWFlMGYtNjA5My00OTViLTk3ZTctNDllZmZlMWI5YzY5IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoia29iaXQiLCJzZXNzaW9uX3N0YXRlIjoiMjE3OGU1ZTItMjcxOC00NDBmLWE5OGItYzFmOTAxOWE4ZGZlIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMta201NSIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsia29iaXQiOnsicm9sZXMiOlsibGhtLWFiLWtvYml0LWJlcmVpY2hzYWRtaW4iLCJsaG0tYWIta29iaXQtemVudHJhbGVyYWRtaW4iXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSByb2xlcyBlbWFpbCIsInNpZCI6IjIxNzhlNWUyLTI3MTgtNDQwZi1hOThiLWMxZjkwMTlhOGRmZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiQ2xlbWVucyBTY2jDvHR6ZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImtvYml0IiwiZ2l2ZW5fbmFtZSI6IkNsZW1lbnMiLCJmYW1pbHlfbmFtZSI6IlNjaMO8dHplIiwiZW1haWwiOiJleC5zY2h1ZXR6ZUBtdWVuY2hlbi5kZSJ9.KfilBNKMH1Y2wF9wkfQQPE6gncztrrVSCymR5-Dtebta2cNw6-ILnzdvzkAh3UwL4YRVE6rBuiNeheTB8107ddKDFisG9RcsxpJ8bR6Uea1_pppQqVLtfV9qPf99ouQOd4odfoq1VDCz6q3D7PMD1IoXOiQxVZbNASqpO1DGuj_L_M_OLPJ4Zb2k5-NnS7pDFeaurVQKxJhTC8ZFjM5VA551XF_bWUJq_gxwP2ovOjzryovelPuS8JQ4HVifCObrN2Msk8FeQ5Nu_VmTWoZ_q7Y7SJzUqgL53uOIzgUhGW-B_73Dd1NI4EKzb_lpVcyitMviY5mz_qfMXAJX0o6kOw";
    private static final String TOKEN_USER =
            "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4Y0JsZnhRdFdmQkVvUEo3YUVabndMQTYzS2l1Y1ZseUlOQm1MRjNoZDZrIn0.eyJleHAiOjE2Nzg4NzIwNjgsImlhdCI6MTY3ODg3MTc2OCwiYXV0aF90aW1lIjoxNjc4ODcxNTA5LCJqdGkiOiIyNDVkYmVkNy1jM2UxLTRiNDgtYTQ2MC1mODFiMmUzNDM2MTgiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg4ODgvcmVhbG1zL0tNNTUiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiODBiZGJhZDktN2Q1Yi00MDhmLWJmNzItNjFjNGQxMThmOTk2IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoia29iaXQiLCJzZXNzaW9uX3N0YXRlIjoiZmMwNWQ5MjMtYzQ3Zi00OTQ2LTk1MjktNmQ4NDIxNmFhNTAyIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMta201NSIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIHJvbGVzIGVtYWlsIiwic2lkIjoiZmMwNWQ5MjMtYzQ3Zi00OTQ2LTk1MjktNmQ4NDIxNmFhNTAyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJrb2JpdCB0ZXN0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdCIsImdpdmVuX25hbWUiOiJrb2JpdCIsImZhbWlseV9uYW1lIjoidGVzdCIsImVtYWlsIjoidGVzdEBtdWVuY2hlbi5kZSJ9.Hkocosf9qMXoPqDxAfFrBGxP2oVdSP2Kk13zLWrsAF9-lAWWHpvyaQ5CNj1PikGb5DaHZXOmj7fowOhE-l1mWnuNcNPjzKmCh6_puSeHLx8uOsgJi7v9T48n5xapAm_ncUG_91HzITAZ5jk1WjVinGouW2l33bebxh09SUMhHPNKpUw10orecwmWDDbwnZhrJ-Ml49ESjYBkcQLl9YvpSFeA5qPvWweWCHPp4QrwuICp531W0jAaJkoZ5-1Mhx9s9IL2qnu6CGLj-Iq0xoT0E265bQSLgPkg555AicgORGk3vCssFJQm-DLBBGBvB9nm939XJYznVTH2i9qSVbU2SA";
    private static final String DEPARTMENT_ADMIN = "lhm-ab-kobit-bereichsadmin";

    private static final String KOBIT_ADMIN = "lhm-ab-kobit-zentraleradmin";

    private JwtTokenUtil jwtTokenUtil;

    @BeforeEach
    void init() {
        jwtTokenUtil = new JwtTokenUtil();
    }

    @Test
    void getRolesFromTokenTest() {
        val roles = jwtTokenUtil.getClientRoles(TOKEN_ADMIN);
        assertThat(roles).hasSize(2);
        assertThat(roles.stream().anyMatch(it -> it.equals(DEPARTMENT_ADMIN))).isTrue();
        assertThat(roles.stream().anyMatch(it -> it.equals(KOBIT_ADMIN))).isTrue();
    }

    @Test
    void getRolesFromTokenNoAdminTest() {
        val roles = jwtTokenUtil.getClientRoles(TOKEN_USER);
        assertThat(roles).hasSize(0);
    }
}
