name: build and test Backend

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.1-jdk-11 # Use appropriate Maven+JDK image as per your project requirements

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        run: mvn --batch-mode clean verify

      - name: Upload test results for JUnit
        uses: actions/upload-artifact@v2
        if: always() # Ensure that test results are uploaded even if the testing step fails
        with:
          name: junit-reports
          path: '**/target/surefire-reports/TEST-*.xml'
  compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Advance Security Policy as Code
        uses: advanced-security/policy-as-code@v2.4.1
        with:
          policy: it-at-m/policy-as-code
          policy-path: default.yaml
          token: ${{ secrets.ACCESS_TOKEN }}
          argvs: "--disable-dependabot --disable-secret-scanning --disable-code-scanning --display"
